Create Account iban fix
Sysmod-2021/bankappbackend pull request #86
Opened 2021-12-10 00:37 UTC by huseynovramilx

Modified create account endpoint to return iban,
Modified saveData to save iban,
Fixed the bank constructor to not duplicate bank account

2021-12-10 06:59 UTC, ira-halenok requested changes

2021-12-10 06:59 UTC, ira-halenok commented on src/main/java/files/customers.txt
> +67b83f8f-3613-497c-9186-503f6a3679d2,gaASDSSDF,DFSDDSA,ASDSD@SD.com,sxIY3VEQYe
There is no need to push all these customers to `main`.

2021-12-10 07:02 UTC, ira-halenok commented
@huseynovramilx we also need to adjust the customers/transactions endpoint and accept IBAN code from UI, load accounts by IBAN and then perform the transaction.
And also there is one more serializer: `CustomerSerializer`, it works with the FE, so we need to add adjustments there, as well.

2021-12-10 08:36 UTC, JonasBerx commented
merged the generated diagrams already. Dont commit the generated diagrams to the branches. Only code

2021-12-11 14:15 UTC, ira-halenok commented
@JonasBerx need your approval on whether we can merge the changes to generated diagrams

2021-12-11 14:17 UTC, ira-halenok approved these changes

2021-12-11 14:41 UTC, merged